CREATE DATABASE `File`;

CREATE TABLE `FileTest`(

	`fno`		INT AUTO_INCREMENT PRIMARY KEY,
	`oName`	VARBINARY(100),
	`sName`	VARBINARY(100),
	`rdate`	DATETIME

);

ALTER TABLE `product` RENAME COLUMN;
